server:
  port: 8082
spring:
  application:
    name: catalog-service
  datasource:
    url: ${CATALOG_DB_URL:jdbc:postgresql://localhost:5432/order_system?currentSchema=catalog}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
integrations:
  internal-api-key: ${INTERNAL_API_KEY:local-development-key}
logging:
  level:
    com.berke.orders: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health
